version: '3.7'
# Example docker-compose 
# See deluge and traefik docs for further info on them

services:
  vpn:
    image: quickc/openvpn-client:latest
    secrets:
      - OVPN_CREDENTIALS
      - OVPN_REMOTE
    external: true
    cap_add:
      - net_admin
    networks:
      - default
    restart: unless-stopped
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ./vpn:/vpn

  traefik:
    image: traefik:latest
    container_name: traefik
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${DIR_PREFIX}/traefik/traefik.toml:/traefik.toml'
      - '${DIR_PREFIX}/traefik/acme.json:/acme.json'
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=traefik'
      - 'traefik.frontend.rule=Host:traefik.${DOMAIN}'
      - 'traefik.docker.network=traefik'
      - 'traefik.port=8080'
    networks:
      - 'default'
      - 'traefik'
    ports:
      - '80:80'
      - '443:443'
    expose:
      - '8080'
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    volumes:
      - '${DIR_PREFIX}/deluge/downloads:/downloads'
      - '${DIR_PREFIX}/deluge/config:/config'
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=deluge'
      - 'traefik.frontend.rule=Host:deluge.${DOMAIN}'
      - 'traefik.port=8112'
    network_mode: 'container:vpnclient'
    restart: unless-stopped

networks:
  default: null
  traefik:
    external: true

secrets:
  OVPN_CREDENTIALS:
    file: credentials
  OVPN_REMOTE:
    file: remote
